# Generated by Django 5.0.4 on 2025-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name', max_length=100)),
                ('date_time', models.DateTimeField(blank=True, help_text='Select date and time', null=True)),
                ('is_true', models.BooleanField(default=False, help_text='Select True or False')),
            ],
        ),
    ]
